# Group web-srv
[webservers]
web-1 ansible_host=93.77.177.8 fqdn=web-1.ru-central1.internal
web-2 ansible_host=89.169.145.253 fqdn=web-2.ru-central1.internal

# Group DB
[databases]
main ansible_host=89.169.151.148 fqdn=main.ru-central1.internal
replica ansible_host=89.169.138.21 fqdn=replica.ru-central1.internal

# Group storage
[storage]
storage ansible_host=93.77.182.119 fqdn=storage.ru-central1.internal